### ISSUE TITLE
dask issues stall Tutorial notebook on binder

### ISSUE THREAD

**Issue by Mikejmnez** [malmans2/oceanspy#336]
* OceanSpy version:
current

Live demo runs well. But importing `dask.distributed.Client` (in the) Tutorial notebook makes it run extremely slow. The following cell:
```python
from dask.distributed import Client

client = Client()
client
```
 yields very long `FileNotFoundError` errors, starting with the following snippet
```unix
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/srv/conda/envs/notebook/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/srv/conda/envs/notebook/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/srv/conda/envs/notebook/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/srv/conda/envs/notebook/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/srv/conda/envs/notebook/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/srv/conda/envs/notebook/lib/python3.10/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/binder/binder/Tutorial.ipynb'
2023-03-29 14:55:41,610 - distributed.nanny - WARNING - Restarting worker
Traceback (most recent call last):
```
ending with
```unix
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/distributed/utils.py", line 742, in wrapper
    return await func(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/distributed/nanny.py", line 545, in _on_worker_exit
    await self.instantiate()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/distributed/nanny.py", line 442, in instantiate
    result = await self.process.start()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/distributed/nanny.py", line 714, in start
    msg = await self._wait_until_connected(uid)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/distributed/nanny.py", line 850, in _wait_until_connected
    await asyncio.sleep(self._init_msg_interval)
  File "/srv/conda/envs/notebook/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError
```

I timed the cell, and it takes 1min 10s to execute. Afterwards, the Tutorial notebook runs fine until the following cell:
```python
# Plot the original domain
%matplotlib inline
ax = od.plot.horizontal_section(varName="Depth")
title = ax.set_title(od.name)
```

It takes very long time (>10 minutes),  although I never waited until it finished.

## Quick patch:
Comment the cell that imports the dask client

```python
%from dask.distributed import Client

%client = Client()
%client
```
Afterwards, the notebook actually runs really fast. This is not a fix, but at the same time I don't think there is anything wrong with oceanspy (that is, nothing to be fixed). 

The tutorial notebook runs fine on Sciserver.

**Comment by Mikejmnez** [comment]
closed by #344
